# Generated by Django 3.1.5 on 2021-01-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='id',
        ),
        migrations.AlterField(
            model_name='branches',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.banks'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='ifsc',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
