# Generated by Django 3.1.5 on 2021-01-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20210118_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='bank_id',
            field=models.IntegerField(),
        ),
    ]
